In [3]:
class Emp:

    count = 0  # contains count of employees
    emps = []  # list of employees

    def __init__(self, name, family, salary, dept):
        self.name = name
        self.family = family
        self.salary = salary
        self.dept = dept

        Emp.count += 1  # count is incremented each time the employee instance is created
        Emp.emps.append(self)  # here we are adding the employee details to the list

    # method to calculate the average salary of the employees
    def average_salary(self):
        return sum(emp.salary for emp in Emp.emps) / Emp.count


# Fulltime Employee class inheriting the Employee class
class Fulltime_Emp(Emp):
    pass

# creating instances for above classes
emp1 = Emp("harry potter", "potter", 80000, "II")
fulltime_emp1 = Fulltime_Emp("albus james", "james", 70000, "Developer")
emp2 = Emp("ron weasley", "weasley", 70000, "Marketing")

# Accessing the classes using instances
print(emp1.average_salary())
print(emp2.average_salary())
print(fulltime_emp1.average_salary())


73333.33333333333
73333.33333333333
73333.33333333333


In [4]:
import numpy as np  # importing the numpy module

sampl = np.random.uniform(low=1, high=20, size=20)  # generating random float values between 1 and 20
reshape_arr = sampl.reshape((4, 5))  # reshaping the vector to a 4x5 dimension

print(reshape_arr)

# replacing the max values with 0 in each row
reshape_arr[np.arange(reshape_arr.shape[0]), np.argmax(reshape_arr, axis=1)] = 0

print(reshape_arr)


[[ 5.66145619  6.28835676 13.52091631  1.13209547 12.53619985]
 [18.95256754 16.69490354  9.60670469  9.06305109 16.56817353]
 [14.65061786  9.6814238   4.13105532 19.71644748 10.59019248]
 [ 6.31073127  1.10178373 13.81122185 15.41171665 17.95861732]]
[[ 5.66145619  6.28835676  0.          1.13209547 12.53619985]
 [ 0.         16.69490354  9.60670469  9.06305109 16.56817353]
 [14.65061786  9.6814238   4.13105532  0.         10.59019248]
 [ 6.31073127  1.10178373 13.81122185 15.41171665  0.        ]]
